# Generated by Django 5.2 on 2025-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('location', models.CharField(max_length=100)),
                ('harvest_days', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='CropPrice',
        ),
    ]
