# Generated by Django 5.2 on 2025-04-28 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_cropproduct_delete_cropprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cropproduct',
            name='image_url',
        ),
        migrations.AddField(
            model_name='cropproduct',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='crop_images/'),
        ),
    ]
